version: '3.8'

services:
  blockchain-web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Syncs your local folder with the container (Hot Reloading)
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
